# Generated by Django 3.2.9 on 2023-03-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('IsAvailable', models.BooleanField(default=True, help_text='もしfalseなら表示ができない')),
                ('helptext', models.CharField(blank=True, help_text='補足が必要な場合', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('IsNeedCheck', models.BooleanField(help_text='部屋の管理者の先生に尋ねる必要があるか')),
                ('IsAvailable', models.BooleanField(default=True, help_text='もしfalseなら表示ができない')),
                ('helptext', models.CharField(blank=True, help_text='補足が必要な場合', max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mainapp.area')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(help_text="文字列。'昼休み'や'放課後'等", max_length=20)),
                ('organization', models.CharField(max_length=20)),
                ('StudentNum', models.CharField(max_length=4)),
                ('teacherSeal', models.CharField(blank=True, help_text='許可をした先生が名前を入力', max_length=20)),
                ('affairsSeal', models.CharField(blank=True, help_text='許可をした教務の方が名前を入力', max_length=20)),
                ('roomSeal', models.CharField(blank=True, help_text='申請した部屋管理の方が名前を入力', max_length=20)),
                ('IsEnd', models.BooleanField(default=False, help_text='部屋の使用が終了したか')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mainapp.room')),
            ],
        ),
    ]
